///////////////////////////////////////////////////////////
//  Coursework.cs
//  Implementation of the Class Coursework
//  Generated by Enterprise Architect
//  Created on:      27-Dec-2020 12:32:30 PM
//  Original author: User
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace E_Rubric_System.BLL
{
	public class Coursework : Item
	{

		private int courseworkID;
		private String courseworkName;
		private DateTime dueDate;
		private int noFileSubmit;
		private int rubricID;

		public Coursework()
		{

		}

		~Coursework()
		{

		}

		/// 
		/// <param name="courseworkID"></param>
		/// <param name="courseworkName"></param>
		/// <param name="dueDate"></param>
		/// <param name="noFile"></param>
		/// <param name="rubricID"></param>
		public Coursework(int courseworkID, string courseworkName, DateTime dueDate, int noFile, int rubricID)
		{
			this.courseworkID = courseworkID;
			this.courseworkName = courseworkName;
			this.dueDate = dueDate;
			this.noFileSubmit = noFile;
			this.rubricID = rubricID;
		}

		/// 
		/// <param name="id"></param>
		public void setCourseworkID(int id)
		{
			this.courseworkID = id;
		}

		public int getCourseworkID()
		{

			return courseworkID;
		}

		/// 
		/// <param name="name"></param>
		public void setCourseworkName(String name)
		{
			this.courseworkName = name;
		}

		public String getCourseworkName()
		{

			return courseworkName;
		}

		/// 
		/// <param name="date"></param>
		public void setDueDate(DateTime date)
		{
			this.dueDate = date;
		}

		public DateTime getDueDate()
		{

			return dueDate;
		}

		public int getNoFileSubmit()
		{

			return noFileSubmit;
		}

		/// 
		/// <param name="no"></param>
		public void setNoFileSubmit(int no)
		{
			this.noFileSubmit = no;
		}

		/// 
		/// <param name="id"></param>
		public void setRubricID(int id)
		{
			this.rubricID = id;
		}

		public int getRubricID()
		{

			return rubricID;
		}

	}//end Coursework

}//end namespace Business