///////////////////////////////////////////////////////////
//  CourseworkHandler.cs
//  Implementation of the Class CourseworkHandler
//  Generated by Enterprise Architect
//  Created on:      24-Dec-2020 5:34:48 PM
//  Original author: User
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using System.Collections;
using E_Rubric_System.DLL.ERSDataSetTableAdapters;
using System.Data;

using E_Rubric_System.BLL;

namespace E_Rubric_System.BLL
{
	public class CourseworkHandler {

		private CourseworkTableAdapter cta;

		public CourseworkHandler(){
			cta = new CourseworkTableAdapter();
		}

		~CourseworkHandler(){

		}


		/// 
		/// <param name="RubricID"></param>
		/// <param name="CourseworkID"></param>
		public void attachRubric(int RubricID, int CourseworkID){
			cta.UpdateCourseworkRubricID(RubricID, CourseworkID);
		}

		/// 
		/// <param name="courseworkID"></param>
		public Coursework getCoursework(int courseworkID){
			var result = cta.selectCoursework(courseworkID);
			Coursework coursework = new Coursework();

			foreach (DataRow row in result)
			{
				var name = row["CourseworkName"].ToString();
				var due = row["DueDate"].ToString();
				var noFile = row["NoFileSubmit"].ToString();
				var rID = row["RubricID"].ToString();
                if (rID.Equals(""))
                {
					rID = "-1";
                }
				var cID = row["CourseworkID"].ToString();
				coursework = new Coursework(Int32.Parse(cID), name, DateTime.Parse(due), Int32.Parse(noFile), Int32.Parse(rID));
			}

			return coursework;
		}

		public CourseworkCollection getAllCoursework(){

			CourseworkCollection courseworks = new CourseworkCollection();

			var result = cta.selectAllCoursework();
			Coursework coursework = null;

			int counter = 0;
			foreach (DataRow row in result)
			{
				var name = row["CourseworkName"].ToString();
				var due = row["DueDate"].ToString();
				var noFile = row["NoFileSubmit"].ToString();

				var rID = -1;

                if (!String.IsNullOrEmpty(row["RubricID"].ToString()))
                {
					rID = Int32.Parse(row["RubricID"].ToString());
				}
				
				var cID = row["CourseworkID"].ToString();
				coursework = new Coursework(Int32.Parse(cID), name, DateTime.Parse(due), Int32.Parse(noFile), rID);

				courseworks[counter] = coursework;
				counter++;
			}

			return courseworks;
		}

	}//end CourseworkHandler

}//end namespace Business